version = 0.1

[default.deploy.parameters]
stack_name = "advitigudagudi-auth"
resolve_s3 = true
s3_prefix = "advitigudagudi-auth"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "arunadminaccess"
parameter_overrides = "GoogleClientId=\"769749190788-9kepmg0ge3ibavp9it6quqjdos52df1u.apps.googleusercontent.com\" GoogleClientSecretArn=\"arn:aws:secretsmanager:ap-south-1:731715767373:secret:advitigudagudi/google-client-secret-WIBbU8\""

[default.global.parameters]
region = "ap-south-1"
