version = 0.1

[default.deploy.parameters]
stack_name = "advitigudagudi-auth"
resolve_s3 = true
s3_prefix = "advitigudagudi-auth"
profile = "arunadminaccess"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
