name: Frontend Deployment Pipeline

on:
  push:
    branches:
      - development
      - main

jobs:
  #########################################################
  # Development Deployment
  #########################################################

  deploy-development:
    if: github.ref == 'refs/heads/development'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shell-app

    steps:
      #########################################################
      # Checkout Repository
      #########################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      #########################################################
      # Setup Node.js
      #########################################################

      - name: Setup Node.js
        uses: actions/setup-node@v4

        with:
          node-version: 20

      #########################################################
      # Install Dependencies
      #########################################################

      - name: Install Dependencies
        run: npm install --include=optional

      #########################################################
      # Verify Github Secrets
      #########################################################

      - name: Verify Vite Environment Variables
        env:
          VITE_COGNITO_DOMAIN: ${{ secrets.VITE_COGNITO_DOMAIN }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          VITE_LOGOUT_URI: ${{ secrets.VITE_LOGOUT_URI }}
          VITE_COGNITO_RESPONSE_TYPE: ${{ secrets.VITE_COGNITO_RESPONSE_TYPE }}
          VITE_COGNITO_SCOPE: ${{ secrets.VITE_COGNITO_SCOPE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

        run: |
          echo "Checking Vite secrets"
          echo "DOMAIN=$VITE_COGNITO_DOMAIN"
          echo "CLIENT=$VITE_COGNITO_CLIENT_ID"
          echo "REDIRECT=$VITE_REDIRECT_URI"
          echo "LOGOUT=$VITE_LOGOUT_URI"
          echo "RESPONSE_TYPE=$VITE_COGNITO_RESPONSE_TYPE"
          echo "SCOPE=$VITE_COGNITO_SCOPE"
          echo "API=$VITE_API_BASE_URL"

      #########################################################
      # Build Frontend
      #########################################################

      - name: Build Frontend

        env:
          VITE_COGNITO_DOMAIN: ${{ secrets.VITE_COGNITO_DOMAIN }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          VITE_LOGOUT_URI: ${{ secrets.VITE_LOGOUT_URI }}
          VITE_COGNITO_RESPONSE_TYPE: ${{ secrets.VITE_COGNITO_RESPONSE_TYPE }}
          VITE_COGNITO_SCOPE: ${{ secrets.VITE_COGNITO_SCOPE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

        run: npm run build

      #########################################################
      # Configure AWS Credentials
      #########################################################

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ap-south-1

      #########################################################
      # Upload Frontend Build
      #########################################################

      - name: Upload Frontend Build

        run: |

          aws s3 sync dist s3://dev.advitigudagudi.com --delete

      #########################################################
      # Invalidate CloudFront Cache
      #########################################################

      - name: Invalidate CloudFront Cache

        run: |

          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

  #########################################################
  # Production Deployment
  #########################################################

  deploy-production:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shell-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      #########################################################
      # Build Production
      #########################################################

      - name: Build Frontend

        env:
          VITE_COGNITO_DOMAIN: ${{ secrets.VITE_COGNITO_DOMAIN }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          VITE_LOGOUT_URI: ${{ secrets.VITE_LOGOUT_URI }}
          VITE_COGNITO_RESPONSE_TYPE: ${{ secrets.VITE_COGNITO_RESPONSE_TYPE }}
          VITE_COGNITO_SCOPE: ${{ secrets.VITE_COGNITO_SCOPE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

        run: npm run build

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ap-south-1

      - name: Upload Frontend Build

        run: |

          aws s3 sync dist s3://app.advitigudagudi.com --delete

      - name: Invalidate CloudFront Cache

        run: |

          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
